Cache:
  module: "lib/cache/cache_fs"
  options:
    cache_membuf:
      initialPageSize: 100000000
      growPageSize: 100000000
      maxPageCount: 10
      minFreeBlockSize: 1024
      cachePath: ".cache_membuf"
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
    cache_fs:
      cachePath: ".cache_fs"