Cache:
  defaultModule: "cache_fs"
  options:
    cache_ram:
      cachePath: ".cache_ram"
      pageSize: 100000000
      maxPageCount: 10
      minFreeBlockSize: 1024
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: true
      highReliabilityOptions:
        reliabilityThreshold: 0
        saveUnreliableVersionArtifacts: true
    cache_fs:
      cachePath: ".cache_fs"
      cleanupOptions:
        expireTimeSpan: "P30D"
        maxCacheSize: 0
      persistence: true
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
      highReliability: true
      highReliabilityOptions:
        reliabilityThreshold: 0
        saveUnreliableVersionArtifacts: true
Mirror:
  options:
    queueProcessDelay: 2000
    connectionIdleTimeout: 10000