Cache:
  defaultModule: "lib/cache/cache_fs"
  options:
    cache_ram:
      initialPageSize: 100000000
      growPageSize: 100000000
      maxPageCount: 10
      minFreeBlockSize: 1024
      cachePath: ".cache_ram"
      persistenceOptions:
        autosave: true
        autosaveInterval: 10000
        throttledSaves: false
    cache_fs:
      cachePath: ".cache_fs"
Mirror:
  options:
    queueProcessDelay: 2000
    connectionIdleTimeout: 10000